name: kaffo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  injectable: ^2.5.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.8.0
  flutter_localization: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  injectable_generator: ^2.7.0
  logger: ^2.4.0
  flutter_gen_runner: ^5.10.0

flutter_gen:
  output: lib/core/gen/
#  generate: true
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
